on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rename file
        run: |
          mv documentation README.md
          git add .
          git commit -m "Rename documentation to README.md"
          git push
